##############################
# Please edit this line to "lucifer_probot" to make the bot run
lucifer_explain_config:" lucifer_probot"
##############################  
bot_token: "1476880088:AAEI7-elLgZ2VH4qea16sgoUuHsaJN821Mo" 
owner_id: "1131653685"  # If you dont know, run the bot and do /id in your private chat with it
api_key: '1383845'  #Owner API Key
api_hash: '0e3d2c299cc3c5cc26c283cecd2eb97c'  #API HASH
owner_username:  "kavinduaj"  #Just write it with the @ ex "@Amazers_xD"
donation_link: "" #paypal etc
support_chat: "@lkhitech # Your telegram support chat username, must have the "@" Example: @MyBotSupportGroupChat
database_url: "postgresql://postgres:dkkaj0123456@postgresql/postgres" # needed for any database modules
message_dump: "None" # needed to make sure 'save from' messages persist
gban_dump: "None" #Channel ID here with the hyphen like -123456789
load: []
no_load: ['translation', 'rss', 'cleaner', 'feds']
cert_path: None
port: 5000
workers: 4
webhook: False
url: None
allow_excl: True
del_cmds: False
strict_gban: True
spammers_lists: [100]
ban_sticker: '' #Preferred Ban sticker btw Ban sticker is disabled :)
whitelist_chats: []
blacklist_chats: []



# API SETUP
cash_api: None # Get one from https://www.alphavantage.co/support/#api-key  
time_api: None # Get one from https://timezonedb.com/register
wall_api: None # Get one from https://wall.alphacoders.com/api.php
lydia_api: None # Coffeehouse chatbot api key, get one from https://coffeehouse.intellivoid.info/
sw_api: None # Get one from t.me/SitiSchu
api_openweather: None # Get one from https://openweather.com

# Permission
dev_users: []
sudo_users: []
support_users: []
whitelist_users: []
